#ifndef __DEVICE_DENONAVR_H__
#define __DEVICE_DENONAVR_H__

#define DENONAVR_MQTT_ON "DENONAVR_MQTT_ON"
#define DENONAVR_MQTT_OFF "DENONAVR_MQTT_OFF"
#define DENONAVR_MQTT_MUTE "DENONAVR_MQTT_MUTE"
#define DENONAVR_MQTT_VOL_UP "DENONAVR_MQTT_VOL_UP"
#define DENONAVR_MQTT_VOL_DOWN "DENONAVR_MQTT_VOL_DOWN"
#define DENONAVR_MQTT_INPUT_BRAY "DENONAVR_MQTT_INPUT_BRAY"
#define DENONAVR_MQTT_INPUT_PS5 "DENONAVR_MQTT_INPUT_PS5"
#define DENONAVR_MQTT_INPUT_SWITCH "DENONAVR_MQTT_INPUT_SWITCH"
#define DENONAVR_MQTT_INPUT_SHIELD "DENONAVR_MQTT_INPUT_SHIELD"
#define DENONAVR_MQTT_SOUND_MODE_MOVIE "DENONAVR_MQTT_SOUND_MODE_MOVIE"

void register_device_denonavr();

#endif /*__DEVICE_DENONAVR_H__*/
