#pragma once

extern uint16_t  SMARTHOME_MQTT_CINEMA_STAIRS_ON;
extern uint16_t  SMARTHOME_MQTT_CINEMA_STAIRS_OFF;
extern uint16_t  SMARTHOME_MQTT_CINEMA_MAIN_ON;
extern uint16_t  SMARTHOME_MQTT_CINEMA_MAIN_OFF;
extern uint16_t  SMARTHOME_MQTT_CINEMA_STAIR_BRIGHTNESS_SET;
extern uint16_t  SMARTHOME_MQTT_CINEMA_MAIN_BRIGHTNESS_SET;


void register_device_smarthome();
